### ISSUE TITLE
你好，我想问一下您的数据集是以多长时间为间隔的？

### ISSUE THREAD

**Issue by miaomiao0502** [Chengfeng-Jia/interacted-ship-predictions#1]
你好，我想问一下您的数据集是以多长时间为间隔的？

**Comment by Chengfeng-Jia** [comment]
您好，原始数据集2秒到26秒不等，在这个工作中，分别将不同轨迹同步到了6秒和18秒两个不同的间隔。

**Comment by miaomiao0502** [comment]
很抱歉打扰您，拜读您的文章后，我还有个问题，就是您文章图11（a）中的船舶轨迹观测时间和预测时间分别是多少

**Comment by Chengfeng-Jia** [comment]
不客气哦，图中的观测和预测时间都是5分钟。
