### ISSUE TITLE
您好，我想问一下您是如何得到船只相遇时的轨迹集的？

### ISSUE THREAD

**Issue by ccbbzz** [Chengfeng-Jia/interacted-ship-predictions#2]
以及数据集划分的细节，非常感谢！

**Comment by Chengfeng-Jia** [comment]
代码上来说很简单，就是相邻时间出现在了相近地点。我是存在了sql数据库，所以检索起来不难，为了避免重复计算距离，我用的方法是geohash。
数据集的划分我试过多种， 训练集50-80%都试过，在我这个方法里，没有特别大的区别，但是这也只是相对的。
而且以上都是自己的一些经验，其实已经超出了这个repository和论文的范畴了

**Comment by ccbbzz** [comment]
好的，非常感谢您的回答！
